### ISSUE TITLE
Error scraping users from Google Drive

### ISSUE THREAD

**Issue by ronnodas** [cardinalitypuzzles/cardboard#832]
I've tried to set up cardboard following the new hunt setup guide but users that the Google Drive folder/files are shared with do not seem to get access to the hunt. In fact, when I try the "Add users from Google Drive" option in hunt editing mode, I get the following traceback in the Heroku logs.
<details>
  <summary>
    Heroku logs
  </summary>
  
```
2024-12-30T21:01:53.410524+00:00 app[worker.1]: Traceback (most recent call last):

2024-12-30T21:01:53.410526+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task

2024-12-30T21:01:53.410526+00:00 app[worker.1]:     R = retval = fun(*args, **kwargs)

2024-12-30T21:01:53.410527+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__

2024-12-30T21:01:53.410527+00:00 app[worker.1]:     return self.run(*args, **kwargs)

2024-12-30T21:01:53.410527+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/celery/app/autoretry.py", line 34, in run

2024-12-30T21:01:53.410527+00:00 app[worker.1]:     return task._orig_run(*args, **kwargs)

2024-12-30T21:01:53.410528+00:00 app[worker.1]:   File "/app/google_api_lib/tasks.py", line 705, in sync_drive_permissions_for_hunt

2024-12-30T21:01:53.410532+00:00 app[worker.1]:     users = UserModel.objects.filter(email__in=emails)

2024-12-30T21:01:53.410533+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method

2024-12-30T21:01:53.410533+00:00 app[worker.1]:     return getattr(self.get_queryset(), name)(*args, **kwargs)

2024-12-30T21:01:53.410533+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/django/db/models/query.py", line 1421, in filter

2024-12-30T21:01:53.410534+00:00 app[worker.1]:     return self._filter_or_exclude(False, args, kwargs)

2024-12-30T21:01:53.410534+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/django/db/models/query.py", line 1439, in _filter_or_exclude

2024-12-30T21:01:53.410534+00:00 app[worker.1]:     clone._filter_or_exclude_inplace(negate, args, kwargs)

2024-12-30T21:01:53.410534+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/django/db/models/query.py", line 1446, in _filter_or_exclude_inplace

2024-12-30T21:01:53.410535+00:00 app[worker.1]:     self._query.add_q(Q(*args, **kwargs))

2024-12-30T21:01:53.410535+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1532, in add_q

2024-12-30T21:01:53.410535+00:00 app[worker.1]:     clause, _ = self._add_q(q_object, self.used_aliases)

2024-12-30T21:01:53.410535+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1562, in _add_q

2024-12-30T21:01:53.410535+00:00 app[worker.1]:     child_clause, needed_inner = self.build_filter(

2024-12-30T21:01:53.410535+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1478, in build_filter

2024-12-30T21:01:53.410536+00:00 app[worker.1]:     condition = self.build_lookup(lookups, col, value)

2024-12-30T21:01:53.410536+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1303, in build_lookup

2024-12-30T21:01:53.410536+00:00 app[worker.1]:     lookup = lookup_class(lhs, rhs)

2024-12-30T21:01:53.410536+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/django/db/models/lookups.py", line 27, in __init__

2024-12-30T21:01:53.410536+00:00 app[worker.1]:     self.rhs = self.get_prep_lookup()

2024-12-30T21:01:53.410536+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/django/db/models/lookups.py", line 426, in get_prep_lookup

2024-12-30T21:01:53.410537+00:00 app[worker.1]:     return super().get_prep_lookup()

2024-12-30T21:01:53.410537+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/django/db/models/lookups.py", line 270, in get_prep_lookup

2024-12-30T21:01:53.410537+00:00 app[worker.1]:     for rhs_value in self.rhs:

2024-12-30T21:01:53.410537+00:00 app[worker.1]: TypeError: 'NoneType' object is not iterable
```
</details>

How should I fix this? The oauth login and creating/renaming spreadsheets features work fine so the Google cloud api access seems to be working otherwise.

For reference, I'm on commit `1861c8d` (also tried using v5.0.1 but got error 500 with something about the static file `main.js` in the logs, and I'm not familiar with Django/... so didn't want to troubleshoot that). Happy to provide other debugging information but I would need guidance on where to look.

As a workaround, if there's an option to set it up so that everyone has access to every hunt that would also be fine (or just disable oauth and have a single user/password login that we share manually).

**Comment by rgossiaux** [comment]
@ronnodas I'm not totally sure why you got that error, but I added some better error handling at least. Are you sure that you have the google drive folder ID set correctly and that you have added individuals' emails to the folder?

**Comment by ronnodas** [comment]
It still doesn't work for me, here are the new logs:

<details>
  <summary>
    Logs from commit a75ff82c
  </summary>
  
```2025-01-10T00:18:23.630312+00:00 app[worker.1]: [2025-01-09 19:18:23,630: WARNING/ForkPoolWorker-2] Traceback (most recent call last):

2025-01-10T00:18:23.630362+00:00 app[worker.1]: [2025-01-09 19:18:23,630: WARNING/ForkPoolWorker-2]   File "/app/.heroku/python/lib/python3.10/logging/__init__.py", line 1100, in emit

2025-01-10T00:18:23.630362+00:00 app[worker.1]:     msg = self.format(record)

2025-01-10T00:18:23.630391+00:00 app[worker.1]: [2025-01-09 19:18:23,630: WARNING/ForkPoolWorker-2]   File "/app/.heroku/python/lib/python3.10/logging/__init__.py", line 943, in format

2025-01-10T00:18:23.630391+00:00 app[worker.1]:     return fmt.format(record)

2025-01-10T00:18:23.630422+00:00 app[worker.1]: [2025-01-09 19:18:23,630: WARNING/ForkPoolWorker-2]   File "/app/.heroku/python/lib/python3.10/site-packages/celery/utils/log.py", line 146, in format

2025-01-10T00:18:23.630423+00:00 app[worker.1]:     msg = super().format(record)

2025-01-10T00:18:23.630450+00:00 app[worker.1]: [2025-01-09 19:18:23,630: WARNING/ForkPoolWorker-2]   File "/app/.heroku/python/lib/python3.10/logging/__init__.py", line 678, in format

2025-01-10T00:18:23.630450+00:00 app[worker.1]:     record.message = record.getMessage()

2025-01-10T00:18:23.630480+00:00 app[worker.1]: [2025-01-09 19:18:23,630: WARNING/ForkPoolWorker-2]   File "/app/.heroku/python/lib/python3.10/logging/__init__.py", line 368, in getMessage

2025-01-10T00:18:23.630480+00:00 app[worker.1]:     msg = msg % self.args

2025-01-10T00:18:23.630515+00:00 app[worker.1]: [2025-01-09 19:18:23,630: WARNING/ForkPoolWorker-2] TypeError: not all arguments converted during string formatting

2025-01-10T00:18:23.630547+00:00 app[worker.1]: [2025-01-09 19:18:23,630: WARNING/ForkPoolWorker-2] Call stack:

2025-01-10T00:18:23.630893+00:00 app[worker.1]: [2025-01-09 19:18:23,630: WARNING/ForkPoolWorker-2]   File "/app/.heroku/python/bin/celery", line 8, in <module>

2025-01-10T00:18:23.630893+00:00 app[worker.1]:     sys.exit(main())

2025-01-10T00:18:23.630921+00:00 app[worker.1]: [2025-01-09 19:18:23,630: WARNING/ForkPoolWorker-2]   File "/app/.heroku/python/lib/python3.10/site-packages/celery/__main__.py", line 15, in main

2025-01-10T00:18:23.630921+00:00 app[worker.1]:     sys.exit(_main())

2025-01-10T00:18:23.630951+00:00 app[worker.1]: [2025-01-09 19:18:23,630: WARNING/ForkPoolWorker-2]   File "/app/.heroku/python/lib/python3.10/site-packages/celery/bin/celery.py", line 217, in main

2025-01-10T00:18:23.630951+00:00 app[worker.1]:     return celery(auto_envvar_prefix="CELERY")

2025-01-10T00:18:23.630979+00:00 app[worker.1]: [2025-01-09 19:18:23,630: WARNING/ForkPoolWorker-2]   File "/app/.heroku/python/lib/python3.10/site-packages/click/core.py", line 1130, in __call__

2025-01-10T00:18:23.630979+00:00 app[worker.1]:     return self.main(*args, **kwargs)

2025-01-10T00:18:23.631006+00:00 app[worker.1]: [2025-01-09 19:18:23,630: WARNING/ForkPoolWorker-2]   File "/app/.heroku/python/lib/python3.10/site-packages/click/core.py", line 1055, in main

2025-01-10T00:18:23.631006+00:00 app[worker.1]:     rv = self.invoke(ctx)

2025-01-10T00:18:23.631032+00:00 app[worker.1]: [2025-01-09 19:18:23,631: WARNING/ForkPoolWorker-2]   File "/app/.heroku/python/lib/python3.10/site-packages/click/core.py", line 1657, in invoke

2025-01-10T00:18:23.631032+00:00 app[worker.1]:     return _process_result(sub_ctx.command.invoke(sub_ctx))

2025-01-10T00:18:23.631059+00:00 app[worker.1]: [2025-01-09 19:18:23,631: WARNING/ForkPoolWorker-2]   File "/app/.heroku/python/lib/python3.10/site-packages/click/core.py", line 1404, in invoke

2025-01-10T00:18:23.631059+00:00 app[worker.1]:     return ctx.invoke(self.callback, **ctx.params)

2025-01-10T00:18:23.631085+00:00 app[worker.1]: [2025-01-09 19:18:23,631: WARNING/ForkPoolWorker-2]   File "/app/.heroku/python/lib/python3.10/site-packages/click/core.py", line 760, in invoke

2025-01-10T00:18:23.631085+00:00 app[worker.1]:     return __callback(*args, **kwargs)

2025-01-10T00:18:23.631111+00:00 app[worker.1]: [2025-01-09 19:18:23,631: WARNING/ForkPoolWorker-2]   File "/app/.heroku/python/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func

2025-01-10T00:18:23.631111+00:00 app[worker.1]:     return f(get_current_context(), *args, **kwargs)

2025-01-10T00:18:23.631138+00:00 app[worker.1]: [2025-01-09 19:18:23,631: WARNING/ForkPoolWorker-2]   File "/app/.heroku/python/lib/python3.10/site-packages/celery/bin/base.py", line 134, in caller

2025-01-10T00:18:23.631138+00:00 app[worker.1]:     return f(ctx, *args, **kwargs)

2025-01-10T00:18:23.631164+00:00 app[worker.1]: [2025-01-09 19:18:23,631: WARNING/ForkPoolWorker-2]   File "/app/.heroku/python/lib/python3.10/site-packages/celery/bin/worker.py", line 351, in worker

2025-01-10T00:18:23.631164+00:00 app[worker.1]:     worker.start()

2025-01-10T00:18:23.631190+00:00 app[worker.1]: [2025-01-09 19:18:23,631: WARNING/ForkPoolWorker-2]   File "/app/.heroku/python/lib/python3.10/site-packages/celery/worker/worker.py", line 203, in start

2025-01-10T00:18:23.631190+00:00 app[worker.1]:     self.blueprint.start(self)

2025-01-10T00:18:23.631216+00:00 app[worker.1]: [2025-01-09 19:18:23,631: WARNING/ForkPoolWorker-2]   File "/app/.heroku/python/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start

2025-01-10T00:18:23.631216+00:00 app[worker.1]:     step.start(parent)

2025-01-10T00:18:23.631242+00:00 app[worker.1]: [2025-01-09 19:18:23,631: WARNING/ForkPoolWorker-2]   File "/app/.heroku/python/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start

2025-01-10T00:18:23.631243+00:00 app[worker.1]:     return self.obj.start()

2025-01-10T00:18:23.631284+00:00 app[worker.1]: [2025-01-09 19:18:23,631: WARNING/ForkPoolWorker-2]   File "/app/.heroku/python/lib/python3.10/site-packages/celery/concurrency/base.py", line 129, in start

2025-01-10T00:18:23.631284+00:00 app[worker.1]:     self.on_start()

2025-01-10T00:18:23.631318+00:00 app[worker.1]: [2025-01-09 19:18:23,631: WARNING/ForkPoolWorker-2]   File "/app/.heroku/python/lib/python3.10/site-packages/celery/concurrency/prefork.py", line 109, in on_start

2025-01-10T00:18:23.631318+00:00 app[worker.1]:     P = self._pool = Pool(processes=self.limit,

2025-01-10T00:18:23.631345+00:00 app[worker.1]: [2025-01-09 19:18:23,631: WARNING/ForkPoolWorker-2]   File "/app/.heroku/python/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 463, in __init__

2025-01-10T00:18:23.631345+00:00 app[worker.1]:     super().__init__(processes, *args, **kwargs)

2025-01-10T00:18:23.631372+00:00 app[worker.1]: [2025-01-09 19:18:23,631: WARNING/ForkPoolWorker-2]   File "/app/.heroku/python/lib/python3.10/site-packages/billiard/pool.py", line 1046, in __init__

2025-01-10T00:18:23.631372+00:00 app[worker.1]:     self._create_worker_process(i)

2025-01-10T00:18:23.631407+00:00 app[worker.1]: [2025-01-09 19:18:23,631: WARNING/ForkPoolWorker-2]   File "/app/.heroku/python/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 480, in _create_worker_process

2025-01-10T00:18:23.631407+00:00 app[worker.1]:     return super()._create_worker_process(i)

2025-01-10T00:18:23.631434+00:00 app[worker.1]: [2025-01-09 19:18:23,631: WARNING/ForkPoolWorker-2]   File "/app/.heroku/python/lib/python3.10/site-packages/billiard/pool.py", line 1158, in _create_worker_process

2025-01-10T00:18:23.631434+00:00 app[worker.1]:     w.start()

2025-01-10T00:18:23.631459+00:00 app[worker.1]: [2025-01-09 19:18:23,631: WARNING/ForkPoolWorker-2]   File "/app/.heroku/python/lib/python3.10/site-packages/billiard/process.py", line 124, in start

2025-01-10T00:18:23.631459+00:00 app[worker.1]:     self._popen = self._Popen(self)

2025-01-10T00:18:23.631493+00:00 app[worker.1]: [2025-01-09 19:18:23,631: WARNING/ForkPoolWorker-2]   File "/app/.heroku/python/lib/python3.10/site-packages/billiard/context.py", line 333, in _Popen

2025-01-10T00:18:23.631493+00:00 app[worker.1]:     return Popen(process_obj)

2025-01-10T00:18:23.631519+00:00 app[worker.1]: [2025-01-09 19:18:23,631: WARNING/ForkPoolWorker-2]   File "/app/.heroku/python/lib/python3.10/site-packages/billiard/popen_fork.py", line 24, in __init__

2025-01-10T00:18:23.631519+00:00 app[worker.1]:     self._launch(process_obj)

2025-01-10T00:18:23.631545+00:00 app[worker.1]: [2025-01-09 19:18:23,631: WARNING/ForkPoolWorker-2]   File "/app/.heroku/python/lib/python3.10/site-packages/billiard/popen_fork.py", line 79, in _launch

2025-01-10T00:18:23.631545+00:00 app[worker.1]:     code = process_obj._bootstrap()

2025-01-10T00:18:23.631571+00:00 app[worker.1]: [2025-01-09 19:18:23,631: WARNING/ForkPoolWorker-2]   File "/app/.heroku/python/lib/python3.10/site-packages/billiard/process.py", line 327, in _bootstrap

2025-01-10T00:18:23.631571+00:00 app[worker.1]:     self.run()

2025-01-10T00:18:23.631598+00:00 app[worker.1]: [2025-01-09 19:18:23,631: WARNING/ForkPoolWorker-2]   File "/app/.heroku/python/lib/python3.10/site-packages/billiard/process.py", line 114, in run

2025-01-10T00:18:23.631598+00:00 app[worker.1]:     self._target(*self._args, **self._kwargs)

2025-01-10T00:18:23.631624+00:00 app[worker.1]: [2025-01-09 19:18:23,631: WARNING/ForkPoolWorker-2]   File "/app/.heroku/python/lib/python3.10/site-packages/billiard/pool.py", line 292, in __call__

2025-01-10T00:18:23.631625+00:00 app[worker.1]:     sys.exit(self.workloop(pid=pid))

2025-01-10T00:18:23.631650+00:00 app[worker.1]: [2025-01-09 19:18:23,631: WARNING/ForkPoolWorker-2]   File "/app/.heroku/python/lib/python3.10/site-packages/billiard/pool.py", line 362, in workloop

2025-01-10T00:18:23.631650+00:00 app[worker.1]:     result = (True, prepare_result(fun(*args, **kwargs)))

2025-01-10T00:18:23.631676+00:00 app[worker.1]: [2025-01-09 19:18:23,631: WARNING/ForkPoolWorker-2]   File "/app/.heroku/python/lib/python3.10/site-packages/celery/app/trace.py", line 649, in fast_trace_task

2025-01-10T00:18:23.631676+00:00 app[worker.1]:     R, I, T, Rstr = tasks[task].__trace__(

2025-01-10T00:18:23.631703+00:00 app[worker.1]: [2025-01-09 19:18:23,631: WARNING/ForkPoolWorker-2]   File "/app/.heroku/python/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task

2025-01-10T00:18:23.631703+00:00 app[worker.1]:     R = retval = fun(*args, **kwargs)

2025-01-10T00:18:23.631728+00:00 app[worker.1]: [2025-01-09 19:18:23,631: WARNING/ForkPoolWorker-2]   File "/app/.heroku/python/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__

2025-01-10T00:18:23.631728+00:00 app[worker.1]:     return self.run(*args, **kwargs)

2025-01-10T00:18:23.631754+00:00 app[worker.1]: [2025-01-09 19:18:23,631: WARNING/ForkPoolWorker-2]   File "/app/.heroku/python/lib/python3.10/site-packages/celery/app/autoretry.py", line 34, in run

2025-01-10T00:18:23.631754+00:00 app[worker.1]:     return task._orig_run(*args, **kwargs)

2025-01-10T00:18:23.631779+00:00 app[worker.1]: [2025-01-09 19:18:23,631: WARNING/ForkPoolWorker-2]   File "/app/google_api_lib/tasks.py", line 709, in sync_drive_permissions_for_hunt

2025-01-10T00:18:23.631780+00:00 app[worker.1]:     logger.warn("Unable to get Google Drive emails for hunt", hunt)

2025-01-10T00:18:23.631819+00:00 app[worker.1]: [2025-01-09 19:18:23,631: WARNING/ForkPoolWorker-2] Message: 'Unable to get Google Drive emails for hunt'

2025-01-10T00:18:23.631819+00:00 app[worker.1]: Arguments: (<Hunt: Mystery Hunt 2025>,)

2025-01-10T00:18:23.631932+00:00 app[worker.1]: [2025-01-09 19:18:23,631: INFO/ForkPoolWorker-2] Task google_api_lib.tasks.sync_drive_permissions_for_hunt[409dbc06-7a69-4370-bae1-88c20d75a92f] succeeded in 0.19387755077332258s: None
```
</details>

Since the spreadsheets are being create/modified correctly in that folder, I assume that means it's not just an error with the drive folder id? I double checked the id for copy-paste errors just in case. Here is a screenshot of the folder's sharing status:
![image](https://github.com/user-attachments/assets/76174e44-15ce-4efb-af54-58c2d2dc38b8)

**Comment by rgossiaux** [comment]
@ronnodas Did you add the Google service account to the folder? See the steps here https://github.com/cardinalitypuzzles/cardboard/blob/main/new-hunt-setup.md#google-drive-setup

**Comment by ronnodas** [comment]
Good catch! I have now but that doesn't seem to have affected the error.
![image](https://github.com/user-attachments/assets/e10dbd71-a79b-4996-80a6-e31bfdfca2a2)

**Comment by rgossiaux** [comment]
@ronnodas Oh it looks like there's a bug when the "Anyone with the link" permission is set. We don't recommend setting this, instead people should be added to this folder individually--not just for cardboard's sake, but also because doing it this way will ensure people's names show up in the Google Sheets instead of Anonymous Animals. 

I think #838 will fix the bug.
